ifneq ($(filter y m, $(CONFIG_TEEGRIS_TEE_SUPPORT)),)
    ccflags-y += -I$(srctree)/drivers/misc/tzdev
    ccflags-y += -I$(srctree)/drivers/misc/tzdev/include
    ccflags-y += -I$(srctree)/drivers/misc/tzdev/include/tzdev
endif
